### ISSUE TITLE
RichText with React Native

### ISSUE THREAD

**Issue by mespeche** [prismicio/prismic-reactjs#43]
Hi !

I have an issue when i use RichText on my React Native application.

With React Native, any text should be in a <Text> component.

Rich text return me an error if I do :
`<RichText render={...} Component="Text"/>`

Same things if I do :
`<RichText render={...} Component={<Text />} />`

Have you got an idea ?

Many thanks ;)

**Comment by codetopixels** [comment]
Did anyone ever find a solution to this please?

**Comment by angeloashmore** [comment]
@codetopixels You should be able to use this component with React Native (I have not tested it myself, however). You will need to provide a custom serializer since the default serializer will return HTML components.

You can see an example here: https://prismic.io/docs/technologies/html-serializer-reactjs#example-with-all-elements

If you are okay using a beta version of this library, I highly recommend it. The v6 beta version of `@prismicio/react` lets you define these components using a simpler syntax.

You can see an example here: https://prismic.io/docs/technical-reference/prismicio-react#prismicrichtext

**Comment by codetopixels** [comment]
That's great, thank you!
